version: "3.9"
services:
  api:
    build: .
    ports:
      - 8000:8000
    environment:
      DATABASE_URL: postgresql://user:pass@db:5432/database
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: database
