"""Add cascade delete to tasks

Revision ID: 193ed813a9c6
Revises: 589ce022ac32
Create Date: 2024-01-14 09:31:06.739008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '193ed813a9c6'
down_revision: Union[str, None] = '589ce022ac32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'content',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('records', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_records_content'), 'records', ['content'], unique=False)
    op.create_index(op.f('ix_records_id'), 'records', ['id'], unique=False)
    op.alter_column('tasks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_tasks_description'), 'tasks', ['description'], unique=False)
    op.create_index(op.f('ix_tasks_id'), 'tasks', ['id'], unique=False)
    op.create_index(op.f('ix_tasks_name'), 'tasks', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_name'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_description'), table_name='tasks')
    op.alter_column('tasks', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_records_id'), table_name='records')
    op.drop_index(op.f('ix_records_content'), table_name='records')
    op.alter_column('records', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('records', 'content',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
