"""Create labels table

Revision ID: 5b7de6c6fc8f
Revises: a2e2c7ea7aae
Create Date: 2024-01-22 20:46:45.144201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7de6c6fc8f'
down_revision: Union[str, None] = 'a2e2c7ea7aae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
