"""Add passive delete to tasks and ondelete cascade to record fk

Revision ID: 86d1f06f3172
Revises: 701e6c89244c
Create Date: 2024-01-14 10:13:35.593885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86d1f06f3172'
down_revision: Union[str, None] = '701e6c89244c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('records_task_id_fkey', 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key('records_task_id_fkey', 'records', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
