"""Increase record content chars allowed

Revision ID: a2e2c7ea7aae
Revises: 86d1f06f3172
Create Date: 2024-01-22 09:02:09.578076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2e2c7ea7aae'
down_revision: Union[str, None] = '86d1f06f3172'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'content',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Unicode(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('records', 'content',
               existing_type=sa.Unicode(length=500),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###
