"""Record add status column

Revision ID: aca12f4c048b
Revises: 5b7de6c6fc8f
Create Date: 2024-01-30 12:38:18.533624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aca12f4c048b'
down_revision: Union[str, None] = '5b7de6c6fc8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('records', sa.Column('status', sa.String(), nullable=True))
    op.create_index(op.f('ix_records_status'), 'records', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_records_status'), table_name='records')
    op.drop_column('records', 'status')
    # ### end Alembic commands ###
