"""Task add next_record_id column

Revision ID: cec5ac1d0494
Revises: aca12f4c048b
Create Date: 2024-01-30 14:47:33.225697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cec5ac1d0494'
down_revision: Union[str, None] = 'aca12f4c048b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('next_record_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_tasks_next_record_id'), 'tasks', ['next_record_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_next_record_id'), table_name='tasks')
    op.drop_column('tasks', 'next_record_id')
    # ### end Alembic commands ###
